### ISSUE TITLE
Icebullet selectable on the water

### ISSUE THREAD

**Issue by Legendary-Ocean** [ProjectKorra/ProjectKorra#1284]
When I set the Dynamic Sourcing setting of the water to false, the ice bullet becomes selectable with water. It leaves gaps in the water. pk reload fixes these spaces.

![224490207-def44723-eb11-43c4-a2dd-db76dfaaac96](https://user-images.githubusercontent.com/83317642/228651442-81a6d201-4de8-42a3-a641-7711e08d8c71.png)

**Comment by Dreig-PSD** [comment]
(fixed in 1.12 PR)

**Comment by Legendary-Ocean** [comment]
Now, if I click shift while looking at snow or water, iceblast goes directly to cooldown. works normally for ice source.

my config settings:

```
  Water:
    DynamicSourcing: false
```

```
    IceBlast:
      Enabled: true
      Damage: 3
      Range: 30
      DeflectRange: 3
      CollisionRadius: 1
      Interval: 0
      Cooldown: 4500
      AllowSnow: true
```
