### ISSUE TITLE
WaterSpout config's SpoutCooldown not working

### ISSUE THREAD

**Issue by Legendary-Ocean** [ProjectKorra/ProjectKorra#1349]
```
WaterSpout:
      Enabled: true
      Cooldown: 4500 (i can still turn on spout but i can't select source to use waterwave)
      Duration: 0
      Height: 12
      Interval: 0
      BlockSpiral: true
      Particles: false
      Wave:
        TrailRevertTime: 1000
        Particles: false
        Enabled: true
        AllowPlantSource: true
        Radius: 3.8
        WaveRadius: 1.5
        SelectRange: 12
        AnimationSpeed: 1
        ChargeTime: 250
        FlightDuration: 2000
        Speed: 2
        Cooldown: 4500 (I cannot select the source to use waterwave, but I can open waterspout. as it's supposed to be)
```

It would be nice if you could make the cooldowns appear separately under the board as WaterSpout and WaterWave.

I wrote this before on Discord, but I thought it would be healthier to report it here, so I wrote it here again.

### Also can you add DynamicCooldown to the spout just like airshield's? pls

> Spigot version: git-Paper-497 (MC: 1.20.4)
> Core Version: 1.12.0-BETA-12

**Comment by Legendary-Ocean** [comment]
It's still the same, I can open spout even though spout is on cooldown. Also, waterspout (wave) is no longer visible when it goes on cooldown. You can make the Spout cooldown appear as "WaterSpout" under the board and when waterspout (wave) goes on cooldown, WaterSpout should be crossed out like before.

```
    WaterSpout:
      Enabled: true
      Cooldown: 9000
      Duration: 0
      Height: 12
      Interval: 0
      BlockSpiral: true
      Particles: false
      SpoutHop:
        Enabled: true
        Power: 0.85
        Cooldown: 0
```

Video: https://youtu.be/M_KdILrjoj8

> Spigot version: git-Paper-497 (MC: 1.20.4)
> Core Version: 1.12.0-BETA-13
