### ISSUE TITLE
Extraction LootChance config doesn't work

### ISSUE THREAD

**Issue by Legendary-Ocean** [ProjectKorra/ProjectKorra#1351]
No matter how much I decrease the Extraction chance values, my chances of getting a double or triple don't seem to change.

```
    Extraction:
      Enabled: true
      SelectRange: 5
      Cooldown: 500
      TripleLootChance: 1
      DoubleLootChance: 1
      IronGolem:
        Drops: 1
        Damage: 4
```

According to my configuration the chance should be 1% but here is the video:

https://youtu.be/OEqNfbwbJ8c

> Spigot version: git-Paper-497 (MC: 1.20.4)
> Core Version: 1.12.0-BETA-12
